### ISSUE TITLE
有个疑问. React在开发模式下这种结构怎么去请求的laravel的程序呢?

### ISSUE THREAD

**Issue by marlonfan** [harryxu/retalk#2]

**Comment by harryxu** [comment]
你是说用webpack的hot loader是吧？

你可以在dev server的那个js里设置一个反向代理，把请求dev server的某些请求转发到你的php服务器地址上。

https://webpack.github.io/docs/webpack-dev-server.html#proxy

**Comment by marlonfan** [comment]
对哦...  是我傻了... 忘记这个了. 因为我一般直接就nginx转发了.
